//! The catalogue: every structure a learner can practise, by level. Its
//! English here is what the model is told; what the learner reads of each
//! (how it is built, when it is used) is in the interface's own languages,
//! under the same key.

use crate::domain::Level;

/// One structure of English.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Structure {
    /// Names it everywhere: in SQLite, on the wire and in the interface.
    pub key: &'static str,
    pub level: Level,
    /// What grammars call it, in English.
    pub name: &'static str,
    /// How it is built.
    pub form: &'static str,
    /// What it is used for; it ends a sentence that begins "used for".
    pub usage: &'static str,
    pub example: &'static str,
}

const fn entry(
    key: &'static str,
    level: Level,
    name: &'static str,
    form: &'static str,
    usage: &'static str,
    example: &'static str,
) -> Structure {
    Structure {
        key,
        level,
        name,
        form,
        usage,
        example,
    }
}

use Level::{Advanced, Basic, Intermediate};

/// In the order the menu lists them: by level, the plainest first.
pub const CATALOGUE: [Structure; 36] = [
    entry(
        "present-simple",
        Basic,
        "Present simple",
        "subject + verb (+ s with he, she, it)",
        "habits, routines and facts",
        "She walks to work every day.",
    ),
    entry(
        "present-continuous",
        Basic,
        "Present continuous",
        "am / is / are + verb-ing",
        "what is happening now or around now",
        "I'm reading a great book.",
    ),
    entry(
        "past-simple",
        Basic,
        "Past simple",
        "verb in the past (-ed or irregular)",
        "a finished action at a past time",
        "We watched a film last night.",
    ),
    entry(
        "was-were",
        Basic,
        "Was / were",
        "was / were + adjective, noun or place",
        "how something or someone was in the past",
        "The food was really good.",
    ),
    entry(
        "going-to",
        Basic,
        "Going to",
        "am / is / are going to + verb",
        "plans already decided",
        "I'm going to call her tomorrow.",
    ),
    entry(
        "will",
        Basic,
        "Will",
        "will / won't + verb",
        "decisions made now, promises and predictions",
        "I'll help you with that.",
    ),
    entry(
        "can",
        Basic,
        "Can / can't",
        "can / can't + verb",
        "ability and possibility",
        "I can't swim very well.",
    ),
    entry(
        "have-to",
        Basic,
        "Have to",
        "have to / has to + verb",
        "what is necessary",
        "I have to get up early tomorrow.",
    ),
    entry(
        "would-like",
        Basic,
        "Would like",
        "would like + noun, or + to + verb",
        "asking for something or saying what one wants, politely",
        "I'd like to try that place.",
    ),
    entry(
        "there-is",
        Basic,
        "There is / there are",
        "there is + singular, there are + plural",
        "saying that something exists",
        "There are two parks near my house.",
    ),
    entry(
        "comparatives",
        Basic,
        "Comparatives",
        "adjective-er than, or more + adjective + than",
        "comparing two things",
        "This phone is cheaper than mine.",
    ),
    entry(
        "superlatives",
        Basic,
        "Superlatives",
        "the + adjective-est, or the most + adjective",
        "the one that stands out in a group",
        "It's the best pizza in town.",
    ),
    entry(
        "present-perfect",
        Intermediate,
        "Present perfect",
        "have / has + past participle",
        "experiences and recent events with no finished time",
        "I've been to Lisbon twice.",
    ),
    entry(
        "present-perfect-continuous",
        Intermediate,
        "Present perfect continuous",
        "have / has been + verb-ing",
        "something that started in the past and still goes on",
        "I've been working here for two years.",
    ),
    entry(
        "past-continuous",
        Intermediate,
        "Past continuous",
        "was / were + verb-ing",
        "an action in progress at a moment in the past",
        "I was cooking when you called.",
    ),
    entry(
        "past-perfect",
        Intermediate,
        "Past perfect",
        "had + past participle",
        "an action that came before another past action",
        "She had already left when I got there.",
    ),
    entry(
        "used-to",
        Intermediate,
        "Used to",
        "used to + verb",
        "a past habit or state that is no longer true",
        "I used to play the piano.",
    ),
    entry(
        "first-conditional",
        Intermediate,
        "First conditional",
        "if + present, will + verb",
        "a real possibility in the future",
        "If it rains, we'll stay home.",
    ),
    entry(
        "second-conditional",
        Intermediate,
        "Second conditional",
        "if + past, would + verb",
        "an imagined or unlikely situation",
        "If I had more time, I'd travel more.",
    ),
    entry(
        "passive",
        Intermediate,
        "Passive",
        "be + past participle",
        "what happens to something, when who does it matters less",
        "The bridge was built in 1920.",
    ),
    entry(
        "relative-clauses",
        Intermediate,
        "Relative clauses",
        "noun + who / which / that + clause",
        "saying which person or thing is meant",
        "The guy who lives next door is a chef.",
    ),
    entry(
        "reported-speech",
        Intermediate,
        "Reported speech",
        "said / told + (that) + clause one tense back",
        "telling what someone said",
        "He said he was tired.",
    ),
    entry(
        "modals-of-deduction",
        Intermediate,
        "Modals of deduction",
        "must / might / can't + verb",
        "how sure one is about something",
        "She must be at work by now.",
    ),
    entry(
        "verb-patterns",
        Intermediate,
        "Verb + -ing or to",
        "verb + verb-ing, or verb + to + verb",
        "a verb that follows another verb",
        "I enjoy cooking, but I forgot to buy rice.",
    ),
    entry(
        "third-conditional",
        Advanced,
        "Third conditional",
        "if + had + past participle, would have + past participle",
        "a past that did not happen and its imagined result",
        "If I'd known, I would have come.",
    ),
    entry(
        "mixed-conditional",
        Advanced,
        "Mixed conditional",
        "if + had + past participle, would + verb",
        "a past that did not happen and its result now",
        "If I'd studied law, I'd be a lawyer now.",
    ),
    entry(
        "wish",
        Advanced,
        "I wish",
        "wish + past, or wish + had + past participle",
        "regretting how things are or were",
        "I wish I'd studied more.",
    ),
    entry(
        "modal-perfect",
        Advanced,
        "Modal perfect",
        "should / might / must + have + past participle",
        "judging or guessing about the past",
        "You should have told me.",
    ),
    entry(
        "future-continuous",
        Advanced,
        "Future continuous",
        "will be + verb-ing",
        "an action in progress at a moment in the future",
        "This time tomorrow I'll be flying to Rome.",
    ),
    entry(
        "future-perfect",
        Advanced,
        "Future perfect",
        "will have + past participle",
        "something finished before a moment in the future",
        "I'll have finished by Friday.",
    ),
    entry(
        "causative",
        Advanced,
        "Causative",
        "have / get + object + past participle",
        "something one arranges for someone else to do",
        "I had my hair cut yesterday.",
    ),
    entry(
        "passive-reporting",
        Advanced,
        "Passive reporting",
        "it is said that, or subject + is said to + verb",
        "what people say or believe, without saying who",
        "He's said to be the best in the country.",
    ),
    entry(
        "cleft",
        Advanced,
        "Cleft sentences",
        "what + clause + is, or it is / was + focus + that",
        "putting the weight on one part of the sentence",
        "What I need is a long holiday.",
    ),
    entry(
        "inversion",
        Advanced,
        "Inversion",
        "never / hardly / not only + auxiliary + subject",
        "emphasis, in careful speech and writing",
        "Never have I seen such a mess.",
    ),
    entry(
        "participle-clauses",
        Advanced,
        "Participle clauses",
        "verb-ing or past participle clause + main clause",
        "joining two actions of the same subject in one sentence",
        "Walking home, I ran into an old friend.",
    ),
    entry(
        "would-rather",
        Advanced,
        "Would rather",
        "would rather + verb, or would rather + subject + past",
        "what one prefers, for oneself or from someone else",
        "I'd rather you didn't tell anyone.",
    ),
];
